AppInmobiliaria/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Master Geographic Location Dictionary</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AppInmobiliaria/force-app/main/default/objects/Location__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Location__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Hierarchy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>City</fullName>
            </value>
            <value>
                <fullName>Neighborhood</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Location__c/fields/Parent_Location__c.field-meta.xml
<CustomField>
    <fullName>Parent_Location__c</fullName>
    <label>Parent Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Sub-Locations</relationshipLabel>
    <relationshipName>Sub_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

AppInmobiliaria/force-app/main/default/classes/LocationSelectorController.cls
public with sharing class LocationSelectorController {
    
    /**
     * Retrieves active locations based on their hierarchy level and parent location.
     * @param level The hierarchy level (Country, State, City, Neighborhood)
     * @param parentId The Id of the parent Location__c (null for Countries)
     * @return List of matching Location__c records
     */
    @AuraEnabled(cacheable=true)
    public static List<Location__c> getLocations(String level, Id parentId) {
        String query = 'SELECT Id, Name, Level__c, Parent_Location__c ' +
                       'FROM Location__c ' +
                       'WHERE Active__c = true AND Level__c = :level ';
        
        /* If a parent is expected but not provided, return empty to prevent massive queries */
        if (String.isNotBlank(parentId)) {
            query += ' AND Parent_Location__c = :parentId ';
        } else if (level != 'Country') {
            return new List<Location__c>(); 
        }
        
        query += ' ORDER BY Name ASC LIMIT 2000';
        return Database.query(query);
    }
}