AppInmobiliaria/force-app/main/default/objects/Cruce__c/Cruce__c.object-meta.xml
<CustomObject>
    <label>Cruce</label>
    <nameField>
        <displayFormat>CRU-{0000}</displayFormat>
        <label>Ref Cruce</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cruces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AppInmobiliaria/force-app/main/default/objects/Cruce__c/fields/Demanda__c.field-meta.xml
<CustomField>
    <fullName>Demanda__c</fullName>
    <label>Demanda</label>
    <referenceTo>Demanda__c</referenceTo>
    <relationshipLabel>Cruces (Propuestas recibidas)</relationshipLabel>
    <relationshipName>Cruces</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Cruce__c/fields/Encargo__c.field-meta.xml
<CustomField>
    <fullName>Encargo__c</fullName>
    <label>Encargo</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cruces (Demandas sugeridas)</relationshipLabel>
    <relationshipName>Cruces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Cruce__c/fields/Estado_Propuesta__c.field-meta.xml
<CustomField>
    <fullName>Estado_Propuesta__c</fullName>
    <label>Estado de Propuesta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nueva Sugerencia</fullName>
                <default>true</default>
                <label>Nueva Sugerencia</label>
            </value>
            <value>
                <fullName>Enviada al Cliente</fullName>
            </value>
            <value>
                <fullName>Visita Programada</fullName>
            </value>
            <value>
                <fullName>Oferta Realizada</fullName>
            </value>
            <value>
                <fullName>Descartada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Demanda__c/Demanda__c.object-meta.xml
<CustomObject>
    <label>Demanda</label>
    <nameField>
        <displayFormat>DEM-{00000}</displayFormat>
        <label>Ref Demanda</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demandas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AppInmobiliaria/force-app/main/default/objects/Demanda__c/fields/Banos_Minimos__c.field-meta.xml
<CustomField>
    <fullName>Banos_Minimos__c</fullName>
    <label>Baños Mínimos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Demanda__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activa</fullName>
                <default>true</default>
                <label>Activa</label>
            </value>
            <value>
                <fullName>En pausa</fullName>
            </value>
            <value>
                <fullName>Satisfecha</fullName>
            </value>
            <value>
                <fullName>Descartada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Demanda__c/fields/Habitaciones_Minimas__c.field-meta.xml
<CustomField>
    <fullName>Habitaciones_Minimas__c</fullName>
    <label>Habitaciones Mínimas</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Demanda__c/fields/Imprescindible_Ascensor__c.field-meta.xml
<CustomField>
    <fullName>Imprescindible_Ascensor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Imprescindible Ascensor</label>
    <type>Checkbox</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Demanda__c/fields/Nombre_del_Interesado__c.field-meta.xml
<CustomField>
    <fullName>Nombre_del_Interesado__c</fullName>
    <formula>Cliente_Interesado__r.FirstName &amp; &quot; &quot; &amp; Cliente_Interesado__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre del Interesado</label>
    <type>Text</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Demanda__c/fields/Poblacion_Deseada__c.field-meta.xml
<CustomField>
    <fullName>Poblacion_Deseada__c</fullName>
    <label>Población Deseada</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Demanda__c/fields/Presupuesto_Maximo__c.field-meta.xml
<CustomField>
    <fullName>Presupuesto_Maximo__c</fullName>
    <label>Presupuesto Máximo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Demanda__c/fields/Provincia_Deseada__c.field-meta.xml
<CustomField>
    <fullName>Provincia_Deseada__c</fullName>
    <label>Provincia Deseada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provincias_Espana</valueSetName>
    </valueSet>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Demanda__c/fields/Tipo_Operacion_Buscada__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Operacion_Buscada__c</fullName>
    <label>Tipo de Operación Buscada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compra</fullName>
                <default>true</default>
                <label>Compra</label>
            </value>
            <value>
                <fullName>Alquiler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Inmueble__c/Inmueble__c.object-meta.xml
<CustomObject>
    <label>Inmueble</label>
    <nameField>
        <displayFormat>INM-{00000}</displayFormat>
        <label>Referencia Inmueble</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inmuebles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AppInmobiliaria/force-app/main/default/objects/Inmueble__c/fields/Banos__c.field-meta.xml
<CustomField>
    <fullName>Banos__c</fullName>
    <label>Baños</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Inmueble__c/fields/Habitaciones__c.field-meta.xml
<CustomField>
    <fullName>Habitaciones__c</fullName>
    <label>Habitaciones</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Inmueble__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provincias_Espana</valueSetName>
    </valueSet>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Inmueble__c/fields/Tiene_Ascensor__c.field-meta.xml
<CustomField>
    <fullName>Tiene_Ascensor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tiene Ascensor</label>
    <type>Checkbox</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Opportunity/fields/Inmueble_Asociado__c.field-meta.xml
<CustomField>
    <fullName>Inmueble_Asociado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inmueble Asociado</label>
    <referenceTo>Inmueble__c</referenceTo>
    <relationshipLabel>Encargos (Oportunidades)</relationshipLabel>
    <relationshipName>Encargos</relationshipName>
    <type>Lookup</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Opportunity/fields/Precio_Salida__c.field-meta.xml
<CustomField>
    <fullName>Precio_Salida__c</fullName>
    <label>Precio de Salida</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

AppInmobiliaria/force-app/main/default/objects/Opportunity/fields/Tipo_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Operacion__c</fullName>
    <label>Tipo de Operación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Venta</fullName>
                <default>true</default>
                <label>Venta</label>
            </value>
            <value>
                <fullName>Alquiler</fullName>
            </value>
            <value>
                <fullName>Traspaso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AppInmobiliaria/force-app/main/default/globalValueSets/Provincias_Espana.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A Coruña</fullName>
    </customValue>
    <customValue>
        <fullName>Álava</fullName>
    </customValue>
    <customValue>
        <fullName>Albacete</fullName>
    </customValue>
    <customValue>
        <fullName>Alicante</fullName>
    </customValue>
    <customValue>
        <fullName>Almería</fullName>
    </customValue>
    <customValue>
        <fullName>Asturias</fullName>
    </customValue>
    <customValue>
        <fullName>Ávila</fullName>
    </customValue>
    <customValue>
        <fullName>Badajoz</fullName>
    </customValue>
    <customValue>
        <fullName>Baleares</fullName>
    </customValue>
    <customValue>
        <fullName>Barcelona</fullName>
    </customValue>
    <customValue>
        <fullName>Burgos</fullName>
    </customValue>
    <customValue>
        <fullName>Cáceres</fullName>
    </customValue>
    <customValue>
        <fullName>Cádiz</fullName>
    </customValue>
    <customValue>
        <fullName>Cantabria</fullName>
    </customValue>
    <customValue>
        <fullName>Castellón</fullName>
    </customValue>
    <customValue>
        <fullName>Ceuta</fullName>
    </customValue>
    <customValue>
        <fullName>Ciudad Real</fullName>
    </customValue>
    <customValue>
        <fullName>Córdoba</fullName>
    </customValue>
    <customValue>
        <fullName>Cuenca</fullName>
    </customValue>
    <customValue>
        <fullName>Gipuzkoa</fullName>
    </customValue>
    <customValue>
        <fullName>Girona</fullName>
    </customValue>
    <customValue>
        <fullName>Granada</fullName>
    </customValue>
    <customValue>
        <fullName>Guadalajara</fullName>
    </customValue>
    <customValue>
        <fullName>Huelva</fullName>
    </customValue>
    <customValue>
        <fullName>Huesca</fullName>
    </customValue>
    <customValue>
        <fullName>Jaén</fullName>
    </customValue>
    <customValue>
        <fullName>La Rioja</fullName>
    </customValue>
    <customValue>
        <fullName>León</fullName>
    </customValue>
    <customValue>
        <fullName>Lleida</fullName>
    </customValue>
    <customValue>
        <fullName>Lugo</fullName>
    </customValue>
    <masterLabel>Provincias España</masterLabel>
</GlobalValueSet>

AppInmobiliaria/force-app/main/default/classes/MatchmakingController.cls
public with sharing class MatchmakingController {

    // Método 1: Lee los datos originales del Encargo (Ahora incluye Baños y Ascensor)
    @AuraEnabled(cacheable=true)
    public static Opportunity getDatosEncargo(Id encargoId) {
        return [SELECT Id, Tipo_Operacion__c, Precio_Salida__c, 
                       Inmueble_Asociado__r.Habitaciones__c, 
                       Inmueble_Asociado__r.Provincia__c,
                       Inmueble_Asociado__r.Banos__c,
                       Inmueble_Asociado__r.Tiene_Ascensor__c
                FROM Opportunity 
                WHERE Id = :encargoId LIMIT 1];
    }

    // Método 2: Busca las demandas (SOQL Dinámico con nuevos filtros de Baños y Ascensor)
    @AuraEnabled(cacheable=true)
    public static List<Demanda__c> getDemandasCompatibles(Id encargoId, String operacion, Decimal presupuesto, Decimal habitaciones, String provincia, Decimal banos, Boolean ascensor) {
        
        List<Cruce__c> crucesPrevios = [SELECT Demanda__c FROM Cruce__c WHERE Encargo__c = :encargoId];
        Set<Id> demandasYaCruzadas = new Set<Id>();
        for (Cruce__c cruce : crucesPrevios) {
            demandasYaCruzadas.add(cruce.Demanda__c);
        }

        String query = 'SELECT Id, Name, Nombre_del_Interesado__c, Presupuesto_Maximo__c, Habitaciones_Minimas__c, Poblacion_Deseada__c ' +
                       'FROM Demanda__c ' +
                       'WHERE Estado__c = \'Activa\' ' +
                       'AND Id NOT IN :demandasYaCruzadas ';
        
        if (String.isNotBlank(operacion)) {
            query += ' AND Tipo_Operacion_Buscada__c = :operacion ';
        }
        if (presupuesto != null) {
            query += ' AND Presupuesto_Maximo__c >= :presupuesto ';
        }
        if (habitaciones != null) {
            query += ' AND Habitaciones_Minimas__c <= :habitaciones ';
        }
        if (banos != null) {
            query += ' AND Banos_Minimos__c <= :banos ';
        }
        if (ascensor != null && ascensor) {
            // Si en el filtro marcamos ascensor, solo buscamos demandas que exijan ascensor
            query += ' AND Imprescindible_Ascensor__c = true ';
        }
        if (String.isNotBlank(provincia)) {
            query += ' AND Provincia_Deseada__c = :provincia ';
        }
        
        query += ' ORDER BY Presupuesto_Maximo__c DESC';

        return Database.query(query);
    }

    @AuraEnabled(cacheable=true)
    public static List<Cruce__c> getCrucesPrevios(Id encargoId) {
        return [SELECT Id, Name, Estado_Propuesta__c, Demanda__c,
                       Demanda__r.Name, 
                       Demanda__r.Nombre_del_Interesado__c, 
                       Demanda__r.Presupuesto_Maximo__c 
                FROM Cruce__c 
                WHERE Encargo__c = :encargoId 
                ORDER BY CreatedDate DESC];
    }

    @AuraEnabled
    public static void crearPropuestas(Id encargoId, List<Id> demandaIds) {
        List<Cruce__c> nuevosCruces = new List<Cruce__c>();
        
        for (Id demandaId : demandaIds) {
            Cruce__c nuevoCruce = new Cruce__c();
            nuevoCruce.Encargo__c = encargoId;
            nuevoCruce.Demanda__c = demandaId;
            nuevoCruce.Estado_Propuesta__c = 'Nueva Sugerencia';
            nuevosCruces.add(nuevoCruce);
        }
     
   
        if (!nuevosCruces.isEmpty()) {
            insert nuevosCruces;
        }
    }
}